Quickstart=0
read_config_descriptions=yes
write_logfile=yes
gui_joystick_control=yes
use_sdl2_render_thread=yes
default_open_gui_key=F12
default_quit_key=
default_correct_aspect_ratio=yes
default_width=640
default_height=512
default_fullscreen=yes
default_retroarch_quit=yes
default_retroarch_menu=yes
default_retroarch_reset=no
default_controller1=joy0
default_mouse1=mouse
